// <auto-generated />
using System;
using KingOfKings.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KingOfKings.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251121075632_AddMonstersAndChineseLocalization")]
    partial class AddMonstersAndChineseLocalization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("KingOfKings.Backend.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpReward")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 5,
                            CurrentHp = 50,
                            Defense = 2,
                            ExpReward = 10,
                            LocationId = 2,
                            MaxHp = 50,
                            Name = "木頭人偶"
                        },
                        new
                        {
                            Id = 2,
                            Attack = 3,
                            CurrentHp = 30,
                            Defense = 1,
                            ExpReward = 5,
                            LocationId = 2,
                            MaxHp = 30,
                            Name = "訓練假人"
                        },
                        new
                        {
                            Id = 3,
                            Attack = 12,
                            CurrentHp = 80,
                            Defense = 5,
                            ExpReward = 25,
                            LocationId = 1,
                            MaxHp = 80,
                            Name = "野狼"
                        },
                        new
                        {
                            Id = 4,
                            Attack = 12,
                            CurrentHp = 80,
                            Defense = 5,
                            ExpReward = 25,
                            LocationId = 1,
                            MaxHp = 80,
                            Name = "wolf"
                        },
                        new
                        {
                            Id = 5,
                            Attack = 8,
                            CurrentHp = 40,
                            Defense = 3,
                            ExpReward = 15,
                            LocationId = 3,
                            MaxHp = 40,
                            Name = "大老鼠"
                        });
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.PlayerCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentMp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerCharacters");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseEffectValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CooldownSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DamageMultiplier")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ManaCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredClass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            BaseEffectValue = 0,
                            CooldownSeconds = 3,
                            DamageMultiplier = 1.5,
                            Description = "A powerful melee attack that deals 1.5x damage",
                            ManaCost = 5,
                            Name = "Bash",
                            RequiredClass = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            BaseEffectValue = 0,
                            CooldownSeconds = 5,
                            DamageMultiplier = 2.0,
                            Description = "A devastating blow that deals 2.0x damage",
                            ManaCost = 10,
                            Name = "Power Strike",
                            RequiredClass = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            BaseEffectValue = 0,
                            CooldownSeconds = 4,
                            DamageMultiplier = 2.0,
                            Description = "Launches a ball of fire dealing 2.0x magic damage",
                            ManaCost = 15,
                            Name = "Fireball",
                            RequiredClass = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            BaseEffectValue = 0,
                            CooldownSeconds = 3,
                            DamageMultiplier = 1.8,
                            Description = "Shoots a shard of ice dealing 1.8x magic damage",
                            ManaCost = 12,
                            Name = "Ice Bolt",
                            RequiredClass = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            BaseEffectValue = 50,
                            CooldownSeconds = 5,
                            DamageMultiplier = 0.0,
                            Description = "Restores health to yourself or an ally",
                            ManaCost = 10,
                            Name = "Heal",
                            RequiredClass = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            BaseEffectValue = 100,
                            CooldownSeconds = 8,
                            DamageMultiplier = 0.0,
                            Description = "A powerful healing spell that restores significant health",
                            ManaCost = 20,
                            Name = "Holy Light",
                            RequiredClass = 2,
                            Type = 1
                        });
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.WorldRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "你站在一個和平村莊的中心。附近有一座噴泉正輕柔地冒著水泡。北邊通往訓練場，東邊是村長的家。",
                            ExitsJson = "{\"n\":2,\"e\":3}",
                            Name = "村莊廣場"
                        },
                        new
                        {
                            Id = 2,
                            Description = "木頭人偶排成一列列站在這裡。空氣中充滿了敲擊木頭的聲音。南邊是村莊廣場。",
                            ExitsJson = "{\"s\":1}",
                            Name = "訓練場"
                        },
                        new
                        {
                            Id = 3,
                            Description = "一間舒適的小屋，空氣中瀰漫著草藥的香味。西邊可以回到村莊廣場。",
                            ExitsJson = "{\"w\":1}",
                            Name = "村長的家"
                        });
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.PlayerCharacter", b =>
                {
                    b.HasOne("KingOfKings.Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("KingOfKings.Backend.Models.CharacterStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("PlayerCharacterId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Con")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Dex")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Int")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Str")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Wis")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PlayerCharacterId");

                            b1.ToTable("PlayerCharacters");

                            b1.WithOwner()
                                .HasForeignKey("PlayerCharacterId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
